### ISSUE TITLE
[BUG] mltk.core.view_model.py  has an install inside

### ISSUE THREAD

**Issue by cdknorow** [SiliconLabs/mltk#1]
Hi, thanks for putting this library together. I noticed the file view_model.py attempts to install a package.

install_pip_package('netron')

I would expect the library dependencies to be filled when installing the mltk package not to occur during the library runtime.

**Comment by sldriedler** [comment]
Thank you for your feedback!

This package was part of the MLTK install script:
https://github.com/SiliconLabs/mltk/blob/master/setup.py

However, as you noticed, it was removed in 0.12.0 and dynamically installed at runtime since the maintainers of the Netron package are purposefully removing old versions from pypi.org which was breaking the mltk install. More details here:
https://github.com/lutzroeder/netron/issues/604

As such, the MLTK setup.py script only installs the critical dependencies, and optional dependencies are installed at runtime as necessary.

Having said that, we could look at adding an additional install option to install all the optional dependencies, e.g.:

```
pip install silabs-mltk[full]
```

**Comment by cdknorow** [comment]
@sldriedler  thanks for the response. It is strange to have packages dynamically installed during runtime so I would recommend against that if possible. It causes all sorts of issues with package managers/python enviornment.

Just FYI for my use case, I installed the package via pip and deployed it to run on a server that did not have internet access.

`pip install silabs-mltk`

Best

**Comment by sldriedler** [comment]
Once again, thank you for the feedback!

I absolutely agree and support for this will be added.

As a workaround, you can install the MLTK with:

```
pip install silabs-mltk netron opencv-python
```

Note that [install_pip_package](https://github.com/SiliconLabs/mltk/blob/master/mltk/utils/python.py#L247) attempts to import the package before installing it.
